/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sessionExporter;

/**
 *
 * @author simond
 */
public class AnonymiseAndSend extends xnatDAO.XNATGUI
{

	/**
	 * Creates new form AnonymiseAndSend
	 */
	public AnonymiseAndSend(java.awt.Frame parent, boolean modal) {

		super(parent, modal);

      initComponents();
      versionJLabel.setText("Version " + version); 
      addListeners();
      implementRestrictions();
      populateCommonComponents();
      populateSpecificComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      ICRLogoJLabel = new javax.swing.JLabel();
      titleLabel = new javax.swing.JLabel();
      versionJLabel = new javax.swing.JLabel();
      poweredByXNATJLabel = new javax.swing.JLabel();
      destProfileJLabel = new javax.swing.JLabel();
      destProfileJComboBox = new javax.swing.JComboBox();
      destProjectJLabel = new javax.swing.JLabel();
      destProjectJComboBox = new javax.swing.JComboBox();
      dataToExportJLabel = new javax.swing.JLabel();
      srcProfileJLabel = new javax.swing.JLabel();
      srcProjectJLabel = new javax.swing.JLabel();
      srcProfileJTextField = new javax.swing.JLabel();
      srcProjectJTextField = new javax.swing.JLabel();
      srcSessionsJLabel = new javax.swing.JLabel();
      srcSessionsJTextField = new javax.swing.JLabel();
      dataDestinationJLabel = new javax.swing.JLabel();
      jLabel11 = new javax.swing.JLabel();
      anonScriptJScrollPane = new javax.swing.JScrollPane();
      anonScriptJTextArea = new javax.swing.JTextArea();
      cancelJButton = new javax.swing.JButton();
      exportJButton = new javax.swing.JButton();
      loadJButton = new javax.swing.JButton();
      saveJButton = new javax.swing.JButton();
      exportProgressJLabel = new javax.swing.JLabel();
      exportProgressJScrollPane = new javax.swing.JScrollPane();
      logJTextArea = new javax.swing.JTextArea();
      exportJProgressBar = new javax.swing.JProgressBar();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      ICRLogoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xnatDAO/projectResources/ICR_fibonacci_logo.jpg"))); // NOI18N

      titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
      titleLabel.setText("Data Exporter");

      versionJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
      versionJLabel.setText("2.0 alpha (3/2/2015)");

      poweredByXNATJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xnatDAO/projectResources/powered_by_XNAT.jpg"))); // NOI18N

      destProfileJLabel.setText("XNAT Profile");

      destProfileJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a profile ..." }));

      destProjectJLabel.setText("XNAT Project");

      destProjectJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a project ..." }));

      dataToExportJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
      dataToExportJLabel.setText("Data to export");

      srcProfileJLabel.setText("XNAT Profile");

      srcProjectJLabel.setText("XNAT Project");

      srcProfileJTextField.setText("No profile specified");

      srcProjectJTextField.setText("No project specified");

      srcSessionsJLabel.setText("Session(s)");

      srcSessionsJTextField.setText("No session specified");

      dataDestinationJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
      dataDestinationJLabel.setText("Data destination");

      jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
      jLabel11.setText("Anonymisation script");

      anonScriptJTextArea.setColumns(20);
      anonScriptJTextArea.setRows(5);
      anonScriptJScrollPane.setViewportView(anonScriptJTextArea);

      cancelJButton.setText("Cancel");

      exportJButton.setText("Export");

      loadJButton.setText("Load ...");

      saveJButton.setText("Save ...");

      exportProgressJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
      exportProgressJLabel.setText("Export progress");

      logJTextArea.setColumns(20);
      logJTextArea.setRows(5);
      exportProgressJScrollPane.setViewportView(logJTextArea);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(ICRLogoJLabel)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(versionJLabel)
                        .addGap(100, 100, 100))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(86, 86, 86)))
                  .addComponent(poweredByXNATJLabel)
                  .addGap(24, 24, 24))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(srcProjectJLabel)
                     .addComponent(srcProfileJLabel)
                     .addComponent(destProfileJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(destProjectJLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(destProfileJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(destProjectJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(exportJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(srcProjectJTextField)
                           .addComponent(srcProfileJTextField)
                           .addComponent(srcSessionsJTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(exportJProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(exportProgressJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                  .addGap(14, 14, 14))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(dataDestinationJLabel)
                     .addComponent(srcSessionsJLabel))
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                     .addComponent(anonScriptJScrollPane))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(loadJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(12, 12, 12))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(dataToExportJLabel)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(exportProgressJLabel)
                  .addGap(73, 73, 73))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(ICRLogoJLabel)
               .addGroup(layout.createSequentialGroup()
                  .addGap(22, 22, 22)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(poweredByXNATJLabel)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versionJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGap(44, 44, 44)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(dataToExportJLabel)
               .addComponent(exportProgressJLabel))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(srcProfileJTextField)
                  .addGap(18, 18, 18)
                  .addComponent(srcProjectJTextField)
                  .addGap(18, 18, 18)
                  .addComponent(srcSessionsJTextField)
                  .addGap(85, 85, 85)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(destProfileJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(exportJButton)
                     .addComponent(destProfileJLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(destProjectJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(destProjectJLabel)))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(srcProfileJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(srcProjectJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(srcSessionsJLabel))
                     .addComponent(exportProgressJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(dataDestinationJLabel))
                     .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(exportJProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGap(33, 33, 33)
            .addComponent(jLabel11)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(saveJButton)
                  .addGap(12, 12, 12)
                  .addComponent(loadJButton)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(cancelJButton))
               .addComponent(anonScriptJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(33, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AnonymiseAndSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AnonymiseAndSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AnonymiseAndSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AnonymiseAndSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				AnonymiseAndSend dialog = new AnonymiseAndSend(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel ICRLogoJLabel;
   private javax.swing.JScrollPane anonScriptJScrollPane;
   private javax.swing.JTextArea anonScriptJTextArea;
   private javax.swing.JButton cancelJButton;
   private javax.swing.JLabel dataDestinationJLabel;
   private javax.swing.JLabel dataToExportJLabel;
   private javax.swing.JComboBox destProfileJComboBox;
   private javax.swing.JLabel destProfileJLabel;
   private javax.swing.JComboBox destProjectJComboBox;
   private javax.swing.JLabel destProjectJLabel;
   private javax.swing.JButton exportJButton;
   private javax.swing.JProgressBar exportJProgressBar;
   private javax.swing.JLabel exportProgressJLabel;
   private javax.swing.JScrollPane exportProgressJScrollPane;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JButton loadJButton;
   private javax.swing.JTextArea logJTextArea;
   private javax.swing.JLabel poweredByXNATJLabel;
   private javax.swing.JButton saveJButton;
   private javax.swing.JLabel srcProfileJLabel;
   private javax.swing.JLabel srcProfileJTextField;
   private javax.swing.JLabel srcProjectJLabel;
   private javax.swing.JLabel srcProjectJTextField;
   private javax.swing.JLabel srcSessionsJLabel;
   private javax.swing.JLabel srcSessionsJTextField;
   private javax.swing.JLabel titleLabel;
   private javax.swing.JLabel versionJLabel;
   // End of variables declaration//GEN-END:variables
}
