/********************************************************************
* Copyright (c) 2015, Institute of Cancer Research
* All rights reserved.
* 
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
* 
* (1) Redistributions of source code must retain the above copyright
*     notice, this list of conditions and the following disclaimer.
* 
* (2) Redistributions in binary form must reproduce the above
*     copyright notice, this list of conditions and the following
*     disclaimer in the documentation and/or other materials provided
*     with the distribution.
* 
* (3) Neither the name of the Institute of Cancer Research nor the
*     names of its contributors may be used to endorse or promote
*     products derived from this software without specific prior
*     written permission.
* 
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
* INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*********************************************************************/

/********************************************************************
* @author Simon J Doran
* Java class: AnonScriptWindow.java
* First created on Oct 20, 2015
* 
* Anonymisation script editing window
*********************************************************************/
package sessionExporter;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.IOUtils;
import org.apache.log4j.Logger;

public class AnonScriptWindow extends javax.swing.JDialog
{
	private File             chooserCurrentDir = null;
	private File             anonScriptFile    = null;
	protected static Logger  logger = Logger.getLogger(AnonymiseAndSend.class);
   private AnonymiseAndSend caller;
   private String[]         defaultScriptNames = {"anonScriptSimple.das",
                                                  "anonScriptInternal.das",
                                                  "anonScriptExternal.das"};
   private String           unsavedScript = null;
   private boolean          ignoreTextAreaEvent = false;
   private boolean          isSaved = false;
	
	/**
	 * Create a new instance of the anonymisation script editing window
	 * @param parent
	 * @param modal
	 * @param anonScriptFile 
	 */
	public AnonScriptWindow(java.awt.Frame parent, boolean modal, AnonymiseAndSend caller)
	{
		super(parent, modal);
      this.caller = caller;
      
      initComponents();	
      addListeners();
      populateScriptJComboBox();
      loadJButton.setEnabled(false);
      saveJButton.setEnabled(false);
      saveAsJButton.setEnabled(false);
      setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jScrollPane1 = new javax.swing.JScrollPane();
      scriptJTextArea = new javax.swing.JTextArea();
      anonScriptJLabel = new javax.swing.JLabel();
      iconJLabel = new javax.swing.JLabel();
      cancelJButton = new javax.swing.JButton();
      saveJButton = new javax.swing.JButton();
      loadJButton = new javax.swing.JButton();
      approveJButton = new javax.swing.JButton();
      scriptJComboBox = new javax.swing.JComboBox<>();
      saveAsJButton = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      scriptJTextArea.setColumns(20);
      scriptJTextArea.setRows(5);
      jScrollPane1.setViewportView(scriptJTextArea);

      anonScriptJLabel.setFont(anonScriptJLabel.getFont().deriveFont(anonScriptJLabel.getFont().getStyle() | java.awt.Font.BOLD, anonScriptJLabel.getFont().getSize()+7));
      anonScriptJLabel.setText("Anonymisation Script");

      iconJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xnatDAO/projectResources/ICR_DataExporter_small.png"))); // NOI18N

      cancelJButton.setText("Cancel");

      saveJButton.setText("Save");

      loadJButton.setText("Load ...");

      approveJButton.setText("Approve");

      scriptJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

      saveAsJButton.setText("Save As...");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1)
               .addGroup(layout.createSequentialGroup()
                  .addGap(198, 198, 198)
                  .addComponent(iconJLabel)
                  .addGap(18, 18, 18)
                  .addComponent(anonScriptJLabel)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGap(25, 25, 25)
                  .addComponent(scriptJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                  .addComponent(loadJButton)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(saveJButton)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(saveAsJButton)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(approveJButton)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cancelJButton)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(anonScriptJLabel)
               .addComponent(iconJLabel))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(cancelJButton)
               .addComponent(saveJButton)
               .addComponent(loadJButton)
               .addComponent(approveJButton)
               .addComponent(scriptJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(saveAsJButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

	private void addListeners()
   {
		cancelJButton.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{            
            dispose();
			}	  
		});
      
      
      approveJButton.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
            caller.anonScriptVerified = true;
            dispose();
			}	  
		});
		
		
		saveJButton.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{            
				scriptSave();
			}	  
		});
      
      
      saveAsJButton.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{            
				scriptSaveAs();
			}	  
		});
		
		
		loadJButton.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{            
				scriptLoad();
			}	  
		});
      
      

      scriptJComboBox.addItemListener(new ItemListener()
      {
         @Override
         public void itemStateChanged(ItemEvent evt)
         {
            scriptJComboBoxItemStateChanged(evt);
         }
      });
      
      
      scriptJTextArea.getDocument().addDocumentListener(new DocumentListener()
      {
         @Override
         public void insertUpdate(DocumentEvent e)
         {
            scriptJTextAreaChanged();
         }

         @Override
         public void removeUpdate(DocumentEvent e)
         {
            scriptJTextAreaChanged();
         }

         @Override
         public void changedUpdate(DocumentEvent e)
         {
            scriptJTextAreaChanged();
         }
                 
      });
	}

	
   private void populateScriptJComboBox()
   {
      DefaultComboBoxModel scriptDcbm  = new DefaultComboBoxModel();
      scriptDcbm.addElement("Simple (retain significant metadata)");
      scriptDcbm.addElement("Internal ICR (thorough)");
      scriptDcbm.addElement("External use (very thorough)");
      scriptDcbm.addElement("Custom");
      scriptJComboBox.setModel(scriptDcbm);
      scriptJComboBox.setSelectedIndex(1);
   }
   
   
   private void populateScriptJTextArea()
	{
		String resourceErrMsg   = "Couldn't read default anonymisation script.\n"
                                + "This shouldn't happen as it resource is supposed"
				                    + "to be packaged with the application jar!";
		String      fileErrMesg = "Couldn't read selected anonymisation script file.\n";
		String      anonScript;
		InputStream resourceIs;
		
		int n = scriptJComboBox.getSelectedIndex();
      
      // While the combo box is being populated, do nothing.
      if (n == -1) return;
      
      if (n < getNumberOfDefaultScripts()) anonScript = getDefaultScript(n);	
      else
		{
         // A custom script       
         if (anonScriptFile == null)
            anonScript = (unsavedScript == null) ? "" : unsavedScript;

         else
         {
            FileInputStream fis = null;
            try
            {
               fis = new FileInputStream(anonScriptFile);
               anonScript = IOUtils.toString(fis, "UTF-8");	
            }
            catch (IOException exIO)
            {
               JOptionPane.showMessageDialog(this,
                                             "Error reading anonymisation script file" + anonScriptFile.getName(),
                                             "File open error",
                                             JOptionPane.ERROR_MESSAGE);
               anonScript = "";
            }
            finally
            {
               if (fis != null)
               try{fis.close();} catch (IOException exIOa){}
            }
         }
		}
		
		scriptJTextArea.setText(anonScript);
	}

      
      
	private void scriptLoad()
	{
		String anonScript;
      int    choice = 2;
		do
		{			
			JFileChooser chooser = new JFileChooser();
		
			FileFilter   filter  = new FileNameExtensionFilter("Anon script (*.das)","das");
			chooser.addChoosableFileFilter(filter);
			chooser.setFileFilter(filter);
			chooser.setCurrentDirectory(chooserCurrentDir);
			chooser.setApproveButtonText("Open");
			chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

			int returnVal  = chooser.showOpenDialog(this);
			chooserCurrentDir = chooser.getCurrentDirectory();
			if (returnVal != JFileChooser.APPROVE_OPTION) return;
			
			String fileErrMsg = "The following error was encountered when \n"
                             + "trying to load the chosen anonymisation script: \n";
         
			File   chosenFile = chooser.getSelectedFile();
			FileInputStream fis;
			try
			{
				fis = new FileInputStream(chooser.getSelectedFile());
				if (chosenFile.length() < 10000) anonScript = IOUtils.toString(fis, "UTF-8");
				else anonScript = "";
			}
			catch (IOException exIO)
			{
				logger.error(fileErrMsg + exIO.getMessage());
				
            JOptionPane.showMessageDialog(this,
                          "The following error was encountered when trying \n"
                        + "to load the chosen anonymisation script:\n"
                        + exIO.getMessage(),
                        "File open error",
                        JOptionPane.ERROR_MESSAGE);
			}
			
			// Check for pathological case of user selecting a very large non-text
			// file by mistake.
			if (chosenFile.length() >= 10000)
			{
				logger.warn("Script file larger than expected.");
            
            Object[] options = {"Cancel", "Reselect...", "Confirm"};
            
				choice  = JOptionPane.showOptionDialog(this,
						  "The anonymisation script file was larger than expected.\n"
						  + "Please confirm that this file is correct or reselect",
						  "Script larger than expected",
						  JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                    null, options, options[1]);
				
				if ((choice == 0) || (choice == JOptionPane.CLOSED_OPTION)) return;
			}
		}
		while (choice != 2);
		
		populateScriptJTextArea();
	}
	
	private void scriptSaveAs()
	{
		String   fileErrMsg = "Couldn't write anonymisation script file chosen.";
		File     chosenFile;	
		Object[] options = {"Cancel", "Re-select...", "Overwrite"};
		int      choice;	
		do
		{
			choice  = 2;
			JFileChooser chooser = new JFileChooser();
		
			FileFilter   filter  = new FileNameExtensionFilter("Anon script (*.das)","das");
			chooser.addChoosableFileFilter(filter);
			chooser.setFileFilter(filter);
			chooser.setApproveButtonText("Save");
			chooser.setCurrentDirectory(chooserCurrentDir);
			chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
			chooser.setDialogType(JFileChooser.SAVE_DIALOG);

			int returnVal  = chooser.showSaveDialog(this);
			chooserCurrentDir = chooser.getCurrentDirectory();
			if (returnVal != JFileChooser.APPROVE_OPTION) return;
					  
			chosenFile = chooser.getSelectedFile();
			
			if (chosenFile.exists())
			{
				choice  = JOptionPane.showOptionDialog(this,
						  "The anonymisation script file chosen already exists.\n"
						  + "Do you want to overwrite it?",
						  "File exists",
						  JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                    null, options, options[1]);
				
				if ((choice == 0) || (choice == JOptionPane.CLOSED_OPTION)) return;
			}
		}
		while (choice != 2);
		
		BufferedWriter writer = null;
		try
		{
			writer = new BufferedWriter(new FileWriter(chosenFile));
			writer.write(scriptJTextArea.getText());
         
         // If write successful, then next time we can just press save.
         anonScriptFile = chosenFile;
         saveJButton.setEnabled(true);
		}
		catch (IOException exIO)
		{
			JOptionPane.showConfirmDialog(this, "There was an error writing out your anonymisation\n"
					                              + "script to file. Please check your file permissions.");
			logger.error(exIO.getMessage());
		}
		finally
		{
			try {writer.close();}
			catch (IOException exIgnore){}		
		}
	}
   
   
   private void scriptSave()
   {
      BufferedWriter writer = null;
		try
		{
			writer = new BufferedWriter(new FileWriter(anonScriptFile));
			writer.write(scriptJTextArea.getText());
		}
		catch (IOException exIO)
		{
			JOptionPane.showConfirmDialog(this, "There was an error writing out your anonymisation\n"
					                              + "script to file. Please check your file permissions.");
         logger.error(exIO.getMessage());
         
         // If writing was unsuccessful for some reason, we need to disallow
         // this save option for next time round.
         anonScriptFile = null;
         saveJButton.setEnabled(false);
		}
		finally
		{
			try {writer.close();}
			catch (IOException exIgnore){}		
		}
   }

   
   private String getDefaultScript(int n)
   {
      String   resourceErrMsg   = "Couldn't read default anonymisation script.\n"
                                + "This shouldn't happen as it resource is supposed"
				                    + "to be packaged with the application jar!";
		String   script = "";  
      
      if ((n < 0) || (n > defaultScriptNames.length-1))
      {
         logger.error("Chosen input script number (" + n + ") out of range.");
      }
      
      else
      {
         InputStream is = AnonymiseAndSend.class.getResourceAsStream(defaultScriptNames[n]);

         if (is == null) logger.error(resourceErrMsg);
         else
         {
            try
            {
               script = IOUtils.toString(is, "UTF-8");
            }
            catch (IOException exIO)
            {
               logger.error(resourceErrMsg + "\n" + exIO.getMessage());
            }
         }
      }
      
      return script;
   }
   
	
	
	
   private void scriptJComboBoxItemStateChanged(ItemEvent evt)
   {
      // Note: There are two passes through this method per click: once to tell you
      // that an item has been deselected and once to say that a new item has been chosen.
      // Do something only on the selection pass.
      if (evt.getStateChange() == ItemEvent.SELECTED)
      {
         if (scriptJComboBox.getSelectedItem().equals("Custom"))
         {
            // Don't do anything if this event was generated by a change
            // to the text area.
            if (ignoreTextAreaEvent)
            {
               ignoreTextAreaEvent = false;
               return;
            }
            
            // Custom script, initially blank, can be loaded, but can't be saved
            // until some text is typed or something is loaded.
            unsavedScript = null;
            loadJButton.setEnabled(true);
            saveJButton.setEnabled(false);
            saveAsJButton.setEnabled(false);
         }
         else
         {
            // Built-in script can't be loaded or saved.
            unsavedScript = null;
            loadJButton.setEnabled(false);
            saveJButton.setEnabled(false);
            saveAsJButton.setEnabled(false);
         }
         
         populateScriptJTextArea();

      }
   }
      
   
   private void scriptJTextAreaChanged()
   {
      unsavedScript = getScriptText();
      
      // We only want to act on genuine edits of the script, not
      // the text change that comes about when one of the default scripts
      // is loaded up.
      for (int i=0; i<getNumberOfDefaultScripts(); i++)
      {
         if (unsavedScript.equals(getDefaultScript(i))) return;
         if (unsavedScript.equals("")) return;
      }
      ignoreTextAreaEvent = true;
      scriptJComboBox.setSelectedItem("Custom");
      saveAsJButton.setEnabled(true);
      loadJButton.setEnabled(true);
   }
   
   
   private void setButtonStates()
   {
      
   }
   
   

   public JButton getApproveJButton()
   {
      return approveJButton; 
   }
	
	
	public String getScriptText()
	{
		return scriptJTextArea.getText();
	}
   
   
   public int getNumberOfDefaultScripts()
   {
      return defaultScriptNames.length;
   }
	
	
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel anonScriptJLabel;
   private javax.swing.JButton approveJButton;
   private javax.swing.JButton cancelJButton;
   private javax.swing.JLabel iconJLabel;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JButton loadJButton;
   private javax.swing.JButton saveAsJButton;
   private javax.swing.JButton saveJButton;
   private javax.swing.JComboBox<String> scriptJComboBox;
   private javax.swing.JTextArea scriptJTextArea;
   // End of variables declaration//GEN-END:variables
}
